### PR TITLE
Make `Object` comparison behavior match `RLMObject` comparison behavior

### LINKED ISSUE #4705: Conformance to Hashable is broken for objects without primary key
Classes deriving from `Object` appear to automatically inherit conformance to `Hashable` due to having `NSObject` as a base class. The implementation of `hashValue` comes from `-[RLMObjectBase hash]`, by way of `NSObject`'s `Hashable` conformance delegating to the object's `hash` property. `-[RLMObjectBase hash]` isn't correct with respect to `-[RLMObjectBase isEqual:]` for objects that don't have a primary key declared, `-hash` will return different values for two objects that compare as equal, which violates the assumptions about how `Hashable` objects are used.

### PR DESCRIPTION
**Pull request by austinzheng**
Breaking change for 3.0
Fixes #4705

### CODE REVIEW

File: RealmSwift/Object.swift [hunk 1]
```diff
@@ -273,12 +273,15 @@ open class Object: RLMObjectBase, ThreadConfined {
      Returns whether two Realm objects are equal.
 
      Objects are considered equal if and only if they are both managed by the same Realm and point to the same
-     underlying object in the database.
+     underlying object in the database. Object comparison only takes place if the object type has a primary key.
```
Comment (bdash) [inline RealmSwift/Object.swift]: I'm not sure what this extra sentence is trying to say?

File: RealmSwift/Object.swift [hunk 2]
```diff
@@ -273,12 +273,15 @@ open class Object: RLMObjectBase, ThreadConfined {
...
 
      - parameter object: The object to compare the receiver to.
      */
-    open override func isEqual(_ object: Any?) -> Bool {
-        return RLMObjectBaseAreEqual(self as RLMObjectBase?, object as? RLMObjectBase)
+    open override func isEqual(to object: Any?) -> Bool {
+        if let object = object as? Object {
+            return RLMObjectBaseAreEqual(self, object)
```
Comment (bdash) [inline RealmSwift/Object.swift]: Shouldn't this only be calling `RLMObjectBaseAreEqual` if the object has a primary key?

The logic in `-[RLMObjectBase isEqual:]` looks like so:
```objc
- (BOOL)isEqual:(id)object {
    if (RLMObjectBase *other = RLMDynamicCast<RLMObjectBase>(object)) {
        if (_objectSchema.primaryKeyProperty) {
            return RLMObjectBaseAreEqual(self, other);
        }
    }
    return [super isEqual:object];
}
```

Comment (bdash) [inline RealmSwift/Object.swift]: Maybe this should just be delegating to `-[RLMObjectBase isEqual:]` rather than reimplementing it?

**Comment by tgoyne** [comment]
There needs to be tests which actually verify the new behavior.

File: RealmSwift/Object.swift (hunk 2 above)
Comment (austinzheng) [inline RealmSwift/Object.swift]: This is supposed to be equivalent to `-[RLMObject isEqualToObject:]`, which is defined explicitly for `RLMObject` and not at all for `RealmSwift.Object`.

Comment (bdash) [inline RealmSwift/Object.swift]: But isn't `isEqual(to:)` what ends up being called by `Equatable`? Surely the semantics therefore need to match those of `-isEqual:`, not our own `-isEqualToObject:`?

Comment (bdash) [inline RealmSwift/Object.swift]: Oh, I see, you've renamed this from `isEqual(_:)`, which was shadowing `RLMObjectBase`'s implementation, to `isEqual(to:)`, which is a _new_ method.

Comment (austinzheng) [inline RealmSwift/Object.swift]: I'm checking it right now, but I'm almost certain `Equatable`'s `==` invokes `isEqual(_ to:)`, not `isEqual(to:)`. Horrendously confusing, unfortunately.

File: RealmSwift/Object.swift (hunk 1 above)
Comment (bdash) [inline RealmSwift/Object.swift]: This new sentence seems incorrect, given the implementation below. `RLMObjectBaseAreEqual` doesn't care if objects have primary keys.

File: RealmSwift/Object.swift (hunk 2 above)
Comment (bdash) [inline RealmSwift/Object.swift]: `-[RLMObject isEqualToObject:]` is implemented like so:
```objc
return [object isKindOfClass:RLMObject.class] && RLMObjectBaseAreEqual(self, object);
```

The new behavior doesn't appear to be equivalent to that (for one, it calls through to `super.isEqual()` if it's passed a non-`Object`). The old implementation that you're replacing looks like it provides the correct behavior?

Comment (austinzheng) [inline RealmSwift/Object.swift]: I believe you are mostly right. Instead of deferring to `super.isEqual()`, it should just return false. However, the old implementation (e.g. the former implementation of `isEqual(_:)`) will throw an Obj-C exception if the other object isn't an `RLMObject`, rather than returning false. I'll fix that.

Comment (bdash) [inline RealmSwift/Object.swift]: How so? The implementation passed `object as? RLMObjectBase` for the argument, which will return nil in that case.

File: RealmSwift/Object.swift (hunk 1 above)
Comment (austinzheng) [inline RealmSwift/Object.swift]: Yes, the sentence should just be excised.

File: RealmSwift/Object.swift (hunk 2 above)
Comment (austinzheng) [inline RealmSwift/Object.swift]: Oh, you're right. I didn't look at the casts inside the function call carefully enough.

File: RealmSwift/Object.swift [hunk 3]
```diff
@@ -277,9 +277,15 @@ open class Object: RLMObjectBase, ThreadConfined {
 
      - parameter object: The object to compare the receiver to.
      */
-    open override func isEqual(_ object: Any?) -> Bool {
+#if os(macOS)
```
Comment (bdash) [inline RealmSwift/Object.swift]: Hmm. Is this necessary due to the weird scripting category that adds methods to NSObject on Mac?

I wonder if we should give this a name that more clearly distinguishes it from `isEqual(_:)`?

File: RealmSwift/Tests/TestCase.swift [hunk 4]
```diff
@@ -113,6 +113,24 @@ class TestCase: XCTestCase {
         queue.sync { }
     }
 
+    /// Check whether two test objects are equal (refer to the same row in the same Realm), even if their models
+    /// don't define a primary key.
+    func assertEqual(_ o1: Object?, _ o2: Object?, fileName: String = #file, lineNumber: UInt = #line) {
+        RLMAssertEqualTestObjects(self, o1, o2, fileName, lineNumber)
```
Comment (bdash) [inline RealmSwift/Tests/TestCase.swift]: Couldn't this be implemented in terms of `Object.isEqual(to:)`, rather than calling into Obj-C and using `RLMObjectBaseAreEqual`?

File: RealmSwift/Object.swift (hunk 3 above)
Comment (austinzheng) [inline RealmSwift/Object.swift]: Yes, it's because of that horrible, horrible method + Swift's `override` annotation requirement.

I'd be alright with giving it a new name, as long as we're aware that doing so will break a bit of symmetry with `RLMObject` (not sure that is even an issue at this point).

File: RealmSwift/Tests/TestCase.swift (hunk 4 above)
Comment (austinzheng) [inline RealmSwift/Tests/TestCase.swift]: Yeah, that's a good idea.

File: RealmSwift/Tests/TestUtils.h [hunk 5]
```diff
@@ -19,18 +19,24 @@
 #import <Foundation/Foundation.h>
 #import <XCTest/XCTestCase.h>
 
+@class RLMObjectBase;
```
Comment (austinzheng) [inline RealmSwift/Tests/TestUtils.h]: Get rid of this forward declaration, and probably all the changes in this file.

**Comment by austinzheng** [comment]
The first four job failures are known CI issues. The object server tests are failing on that execrable child process issue.

**Comment by austinzheng** [comment]
This is ready for review.

File: RealmSwift/Tests/TestCase.swift [hunk 6]
```diff
@@ -113,6 +113,29 @@ class TestCase: XCTestCase {
...
+            inFile: fileName, atLine: lineNumber, expected: false)
+    }
+
+    /// Check whether two collections containing Realm objects are equal.
+    func assertEqualObjectCollections<T: Collection, U: Collection>(_ c1: T, _ c2: U, fileName: String = #file, lineNumber: UInt = #line)
+        where T.Iterator.Element : Object,
+        U.Iterator.Element : Object,
+        T.IndexDistance : Equatable,
+        T.IndexDistance == U.IndexDistance {
+        XCTAssertEqual(c1.count, c2.count, "Collection counts were incorrect")
```
Comment (jpsim) [inline RealmSwift/Tests/TestCase.swift]: this should forward the `fileName` and `lineNumber` parameters.

File: RealmSwift/Tests/TestCase.swift [hunk 7]
```diff
@@ -113,6 +113,29 @@ class TestCase: XCTestCase {
         queue.sync { }
     }
 
+    /// Check whether two test objects are equal (refer to the same row in the same Realm), even if their models
+    /// don't define a primary key.
+    func assertEqual(_ o1: Object?, _ o2: Object?, fileName: String = #file, lineNumber: UInt = #line) {
+        if o1?.isSameObject(as: o2) ?? false {
```
Comment (jpsim) [inline RealmSwift/Tests/TestCase.swift]: if `o1` is `nil` but `o2` is not, `assertEqual` won't trigger an XCTest failure.

File: CHANGELOG.md [hunk 8]
```diff
@@ -33,10 +33,14 @@ x.x.x Release notes (yyyy-MM-dd)
 * The return types of the `SyncError.clientResetInfo()` and
   `SyncError.deleteRealmUserInfo()` APIs have been changed. They now return
   `RLMSyncErrorActionToken`s or `SyncError.ActionToken`s instead of closures.
+* Swift `Object` comparison and hashing behavior now works the same way as
+  that of `RLMObject` (objects are now only considered equatable if their
+  model class defines a primary key).
```
Comment (bdash) [inline CHANGELOG.md]: I'm a little confused by this. Objects without primary keys can still be compared, it's just based on object identity in that case.

Comment (austinzheng) [inline CHANGELOG.md]: Yes, this should be changed. NSObjects are always `Equatable` according to Swift; the change now is that we don't break the contract for hash values anymore.

File: RealmSwift/Object.swift [hunk 9]
```diff
@@ -266,17 +266,22 @@ open class Object: RLMObjectBase, ThreadConfined {
...
-     Returns whether two Realm objects are equal.
+     Returns whether two Realm objects are the same.
 
-     Objects are considered equal if and only if they are both managed by the same Realm and point to the same
-     underlying object in the database.
+     Objects are considered the same if and only if they are both managed by the same
+     Realm and point to the same underlying object in the database.
+     
+     - note: Equality comparison is implemented by `isEqual(_:)`, but objects are only
+             considered equatable using `==` or `isEqual(_:)` if a primary key is
```
Comment (bdash) [inline RealmSwift/Object.swift]: Again, this comment doesn't seem to match the implementation. Objects without a primary key can be compared, they're just compared using object identity rather than checking if they refer to the same underlying object in the Realm.

File: RealmSwift/Object.swift [hunk 10]
```diff
@@ -266,17 +266,23 @@ open class Object: RLMObjectBase, ThreadConfined {
...
+             is defined with a primary key, `isEqual(_:)` behaves identically to this
+             method. If the object type is not defined with a primary key,
+             `isEqual(_:)` uses the `NSObject` behavior of comparing object identity.
+             This method can be used to compare two objects for database equality
+             whether or not their object type defines a primary key.
 
      - parameter object: The object to compare the receiver to.
      */
-    open override func isEqual(_ object: Any?) -> Bool {
+    public func isSameObject(as object: Any?) -> Bool {
```
Comment (jpsim) [inline RealmSwift/Object.swift]: Should this take an `object: Self?` rather than `Any?`?

File: RealmSwift/Tests/RealmCollectionTypeTests.swift [hunk 11]
```diff
@@ -689,7 +689,7 @@ class ResultsWithCustomInitializerTest: TestCase {
         let expected = Array(collection.map { $0.stringCol })
         let actual = collection.value(forKey: "stringCol") as! [String]!
         XCTAssertEqual(expected, actual!)
-        XCTAssertEqual(collection.map { $0 }, collection.value(forKey: "self") as! [CTTStringObjectWithLink])
+        assertEqualObjectCollections(collection.map { $0 }, collection.value(forKey: "self") as! [SwiftCustomInitializerObject])
```
Comment (jpsim) [inline RealmSwift/Tests/RealmCollectionTypeTests.swift]: How was this test passing before?

Unrelated to this PR, but we should rename `ResultsWithCustomInitializerTest` to `ResultsWithCustomInitializerTests` to match our test case naming convention.

Comment (austinzheng) [inline RealmSwift/Tests/RealmCollectionTypeTests.swift]: May as well take the opportunity to rename it now.

Not sure why that test didn't fail before. Probably something to do with how XCTAssertEqual is implemented? The more I look at the old version of this test case the more confused I am.

File: RealmSwift/Tests/TestCase.swift [hunk 12]
```diff
@@ -113,6 +113,32 @@ class TestCase: XCTestCase {
         queue.sync { }
     }
 
+    /// Check whether two test objects are equal (refer to the same row in the same Realm), even if their models
+    /// don't define a primary key.
+    func assertEqual(_ o1: Object?, _ o2: Object?, fileName: StaticString = #file, lineNumber: UInt = #line) {
```
Comment (jpsim) [inline RealmSwift/Tests/TestCase.swift]: Some suggestions:

```diff
-    func assertEqual(_ o1: Object?, _ o2: Object?, fileName: StaticString = #file, lineNumber: UInt = #line) {
+    func assertEqual<O: Object>(_ o1: O?, _ o2: O?, fileName: StaticString = #file, lineNumber: UInt = #line) {
         if o1 == nil && o2 == nil {
             return
         }
         if let o1 = o1, let o2 = o2, o1.isSameObject(as: o2) {
             return
         }
-        recordFailure(withDescription: "Objects expected to be equal, but weren't. First: \(o1?.description ?? "nil"), "
-            + "second: \(o2?.description ?? "nil")",
-            inFile: String(describing: fileName), atLine: lineNumber, expected: false)
+        XCTFail("Objects expected to be equal, but weren't. First: \(String(describing: o1)), "
+            + "second: \(String(describing: o2))", file: fileName, line: lineNumber)
     }
 
     /// Check whether two collections containing Realm objects are equal.
-    func assertEqualObjectCollections<T: Collection, U: Collection>(_ c1: T, _ c2: U, fileName: StaticString = #file, lineNumber: UInt = #line)
-        where T.Iterator.Element : Object,
-        U.Iterator.Element : Object,
-        T.IndexDistance : Equatable,
-        T.IndexDistance == U.IndexDistance {
+    func assertEqualObjectCollections<C: Collection>(_ c1: C, _ c2: C, fileName: StaticString = #file, lineNumber: UInt = #line)
+        where C.Iterator.Element: Object, C.IndexDistance: Equatable {
             XCTAssertEqual(c1.count, c2.count, "Collection counts were incorrect", file: fileName, line: lineNumber)
             for (o1, o2) in zip(c1, c2) {
                 assertEqual(o1, o2, fileName: fileName, lineNumber: lineNumber)
```
