### PR TITLE
Fix a crash on non-@objc `String?` properties

### LINKED ISSUE #5781: Realm Crashing on Read/ Write operator bool() const
## Goals
Prevent crash
## Expected Results
DB Operates normally

## Actual Results
Crahsed

```

# OS Version: 11.3.1 (15E302)
# Device: iPhone 6 Plus
# RAM Free: 7.8%
# Disk Free: 60.8%

#0. Crashed: com.apple.main-thread
0  Realm                          0x102968468 RLMGetOptional + 60
1  Realm                          0x102908a54 RLMAccessorContext::propertyValue(objc_object*, unsigned long, RLMProperty*) + 804
2  Realm                          0x10290a568 RLMAccessorContext::value_for_property(objc_object*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) + 156
3  Realm                          0x102957a40 realm::Object realm::Object::create<objc_object* __strong, RLMAccessorContext>(RLMAccessorContext&, std::__1::shared_ptr<realm::Realm> const&, realm::ObjectSchema const&, objc_object* __strong, bool, realm::BasicRow<realm::Table>*) + 2908
4  Realm                          0x102956d44 RLMAddObjectToRealm + 596
5  RealmSwift                     0x1033b7a98 _T010RealmSwift0A0C3addyAA6ObjectC_Sb6updatetF + 724
6  MyAppName                      0x100d02a04 TodayVC.(getDataFromServer(Bool, isServerSync : Bool) -> ()).(closure #1).(closure #1) (TodayVC.swift:400)
7  RealmSwift                     0x1033b7350 _T010RealmSwift0A0C5writeyyyKcKF + 80
8  MyAppName                      0x100d02014 TodayVC.(getDataFromServer(Bool, isServerSync : Bool) -> ()).(closure #1) (TodayVC.swift:398)
9  MyAppName                      0x1011166bc static MyAppNameDaysDataModel.get(UIViewController, withMessage : String, withCompletion : (MyAppNameDaysDataModel?) -> (), withError : () -> ()) -> () empty-list Bool (MyAppNameDaysDataModel.swift:119)
10 MyAppName                      0x101094198 APIManager.getTodaysData(UIViewController, withProgressMessage : String?, withCmpletion : (Bool, MyAppNameDaysDataModel?) -> ()) -> () empty-list DataResponse empty-list withCmpletion (APIManager.swift:190)
11 MyAppName                      0x1010947d4 DataResponse<MyAppNameDaysDataModel> (APIManager.swift)
12 Alamofire                      0x101b40f80 _T09Alamofire11DataRequestC8responseACXDSo13DispatchQueueCSg5queue_x0D10SerializeryAA0B8ResponseVy16SerializedObjectQzGc17completionHandlertAA0biH8ProtocolRzlFyycfU_yycfU_ + 236
13 Alamofire                      0x101b0bda8 _T0Ieg_IeyB_TR + 52
14 libdispatch.dylib              0x183cdcb24 _dispatch_call_block_and_release
15 libdispatch.dylib              0x183cdcae4 _dispatch_client_callout
16 libdispatch.dylib              0x183ce96e0 _dispatch_main_queue_callback_4CF$VARIANT$mp
17 CoreFoundation                 0x184393070 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation                 0x184390bc8 __CFRunLoopRun + 2272
19 CoreFoundation                 0x1842b0da8 CFRunLoopRunSpecific + 552
20 GraphicsServices               0x186293020 GSEventRunModal + 100
21 UIKit                          0x18e29178c UIApplicationMain + 236
22 MyAppName                      0x100e4fb10 main (AppDelegate.swift:23)
23 libdyld.dylib                  0x183d41fc0 start + 4

--

#0. Crashed: com.apple.main-thread
0  Realm                          0x102968468 RLMGetOptional + 60
1  Realm                          0x102908a54 RLMAccessorContext::propertyValue(objc_object*, unsigned long, RLMProperty*) + 804
2  Realm                          0x10290a568 RLMAccessorContext::value_for_property(objc_object*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) + 156
3  Realm                          0x102957a40 realm::Object realm::Object::create<objc_object* __strong, RLMAccessorContext>(RLMAccessorContext&, std::__1::shared_ptr<realm::Realm> const&, realm::ObjectSchema const&, objc_object* __strong, bool, realm::BasicRow<realm::Table>*) + 2908
4  Realm                          0x102956d44 RLMAddObjectToRealm + 596
5  RealmSwift                     0x1033b7a98 _T010RealmSwift0A0C3addyAA6ObjectC_Sb6updatetF + 724
6  MyAppName                      0x100d02a04 TodayVC.(getDataFromServer(Bool, isServerSync : Bool) -> ()).(closure #1).(closure #1) (TodayVC.swift:400)
7  RealmSwift                     0x1033b7350 _T010RealmSwift0A0C5writeyyyKcKF + 80
8  MyAppName                      0x100d02014 TodayVC.(getDataFromServer(Bool, isServerSync : Bool) -> ()).(closure #1) (TodayVC.swift:398)
9  MyAppName                      0x1011166bc static MyAppNameDaysDataModel.get(UIViewController, withMessage : String, withCompletion : (MyAppNameDaysDataModel?) -> (), withError : () -> ()) -> () empty-list Bool (MyAppNameDaysDataModel.swift:119)
10 MyAppName                      0x101094198 APIManager.getTodaysData(UIViewController, withProgressMessage : String?, withCmpletion : (Bool, MyAppNameDaysDataModel?) -> ()) -> () empty-list DataResponse empty-list withCmpletion (APIManager.swift:190)
11 MyAppName                      0x1010947d4 DataResponse<MyAppNameDaysDataModel> (APIManager.swift)
12 Alamofire                      0x101b40f80 _T09Alamofire11DataRequestC8responseACXDSo13DispatchQueueCSg5queue_x0D10SerializeryAA0B8ResponseVy16SerializedObjectQzGc17completionHandlertAA0biH8ProtocolRzlFyycfU_yycfU_ + 236
13 Alamofire                      0x101b0bda8 _T0Ieg_IeyB_TR + 52
14 libdispatch.dylib              0x183cdcb24 _dispatch_call_block_and_release
15 libdispatch.dylib              0x183cdcae4 _dispatch_client_callout
16 libdispatch.dylib              0x183ce96e0 _dispatch_main_queue_callback_4CF$VARIANT$mp
17 CoreFoundation                 0x184393070 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation                 0x184390bc8 __CFRunLoopRun + 2272
19 CoreFoundation                 0x1842b0da8 CFRunLoopRunSpecific + 552
20 GraphicsServices               0x186293020 GSEventRunModal + 100
21 UIKit                          0x18e29178c UIApplicationMain + 236
22 MyAppName                      0x100e4fb10 main (AppDelegate.swift:23)
23 libdyld.dylib                  0x183d41fc0 start + 4

#1. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18400feb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#2. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18400feb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#3. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x183e4fe08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183e4fc80 mach_msg + 72
2  CoreFoundation                 0x184392e40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x184390908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x1842b0da8 CFRunLoopRunSpecific + 552
5  Foundation                     0x184d25674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x184d254dc -[NSRunLoop(NSRunLoop) runUntilDate:] + 84
7  UIKit                          0x18df767e4 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x184e35efc __NSThread__start__ + 1040
9  libsystem_pthread.dylib        0x184011220 _pthread_body + 272
10 libsystem_pthread.dylib        0x184011110 _pthread_body + 290
11 libsystem_pthread.dylib        0x18400fb10 thread_start + 4

#4. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18400feb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#5. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18400feb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#6. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18400feb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#7. RLMRealm notification listener
0  libsystem_kernel.dylib         0x183e5434c kevent + 8
1  Realm                          0x102830214 realm::_impl::ExternalCommitHelper::listen() + 412
2  Realm                          0x10283470c realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0::operator()() const + 28
3  Realm                          0x1028346e4 _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEE9__executeIJEEEvNS_15__tuple_indicesIJXspT_EEEE + 64
4  Realm                          0x102834698 std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() + 24
5  Realm                          0x1028345a8 std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() + 36
6  Realm                          0x102835294 std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) + 496
7  libsystem_pthread.dylib        0x184011220 _pthread_body + 272
8  libsystem_pthread.dylib        0x184011110 _pthread_body + 290
9  libsystem_pthread.dylib        0x18400fb10 thread_start + 4

#8. com.twitter.crashlytics.ios.MachExceptionServer
0  MyAppName                      0x10114a2a0 CLSProcessRecordAllThreads
1  MyAppName                      0x10114a2a0 CLSProcessRecordAllThreads
2  MyAppName                      0x10114a15c CLSProcessRecordAllThreads
3  MyAppName                      0x101139628 CLSHandler
4  MyAppName                      0x1011342d8 CLSMachExceptionServer
5  libsystem_pthread.dylib        0x184011220 _pthread_body + 272
6  libsystem_pthread.dylib        0x184011110 _pthread_body + 290
7  libsystem_pthread.dylib        0x18400fb10 thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18400feb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#10. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1840100a0 _pthread_wqthread + 1420
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#11. Thread
0  libsystem_pthread.dylib        0x18400fb04 start_wqthread + 122

#12. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x183e4fe08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183e4fc80 mach_msg + 72
2  CoreFoundation                 0x184392e40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x184390908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x1842b0da8 CFRunLoopRunSpecific + 552
5  CFNetwork                      0x184bbe4b0 -[__CoreSchedulingSetRunnable runForever] + 220
6  Foundation                     0x184e35efc __NSThread__start__ + 1040
7  libsystem_pthread.dylib        0x184011220 _pthread_body + 272
8  libsystem_pthread.dylib        0x184011110 _pthread_body + 290
9  libsystem_pthread.dylib        0x18400fb10 thread_start + 4

#13. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x183e4fe08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183e4fc80 mach_msg + 72
2  CoreFoundation                 0x184392e40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x184390908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x1842b0da8 CFRunLoopRunSpecific + 552
5  Foundation                     0x184d25674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  MyAppName                      0x101262b40 -[_FSRRunLoopThread main]
7  Foundation                     0x184e35efc __NSThread__start__ + 1040
8  libsystem_pthread.dylib        0x184011220 _pthread_body + 272
9  libsystem_pthread.dylib        0x184011110 _pthread_body + 290
10 libsystem_pthread.dylib        0x18400fb10 thread_start + 4

#14. Thread
0  libsystem_kernel.dylib         0x183e71d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1840100a0 _pthread_wqthread + 1420
2  libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#15. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x183e71538 __select + 8
1  CoreFoundation                 0x18439b378 __CFSocketManager + 644
2  libsystem_pthread.dylib        0x184011220 _pthread_body + 272
3  libsystem_pthread.dylib        0x184011110 _pthread_body + 290
4  libsystem_pthread.dylib        0x18400fb10 thread_start + 4

#16. Thread
0  libsystem_pthread.dylib        0x18400fb04 start_wqthread + 122

#17. NSOperationQueue 0x10448e2a0 (QOS: UTILITY)
0  CoreFoundation                 0x184394c24 _CFRelease + 192
1  CoreFoundation                 0x1842b514c -[__NSArrayI dealloc] + 64
2  CoreFoundation                 0x1842bc5b4 -[__NSDictionaryI dealloc] + 136
3  CoreFoundation                 0x1842bc5b4 -[__NSDictionaryI dealloc] + 136
4  CoreFoundation                 0x1842b514c -[__NSArrayI dealloc] + 64
5  CoreFoundation                 0x1842bc5b4 -[__NSDictionaryI dealloc] + 136
6  CoreFoundation                 0x1842b514c -[__NSArrayI dealloc] + 64
7  CoreFoundation                 0x1842bc5b4 -[__NSDictionaryI dealloc] + 136
8  CoreFoundation                 0x1842bc5b4 -[__NSDictionaryI dealloc] + 136
9  CoreFoundation                 0x1842b514c -[__NSArrayI dealloc] + 64
10 CoreFoundation                 0x1842bc5b4 -[__NSDictionaryI dealloc] + 136
11 CoreFoundation                 0x1842bc5b4 -[__NSDictionaryI dealloc] + 136
12 libobjc.A.dylib                0x1835c213c (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 844
13 CoreFoundation                 0x1842b0aac _CFAutoreleasePoolPop + 28
14 Foundation                     0x184d53f60 -[__NSOperationInternal _start:] + 1540
15 libdispatch.dylib              0x183cdcae4 _dispatch_client_callout
16 libdispatch.dylib              0x183ce41f4 _dispatch_block_invoke_direct$VARIANT$mp
17 libdispatch.dylib              0x183cdcae4 _dispatch_client_callout
18 libdispatch.dylib              0x183ce41f4 _dispatch_block_invoke_direct$VARIANT$mp
19 libdispatch.dylib              0x183ce40e0 dispatch_block_perform$VARIANT$mp
20 Foundation                     0x184e14750 __NSOQSchedule_f + 376
21 libdispatch.dylib              0x183cdcae4 _dispatch_client_callout
22 libdispatch.dylib              0x183ce4f18 _dispatch_continuation_pop$VARIANT$mp
23 libdispatch.dylib              0x183ce3850 _dispatch_async_redirect_invoke$VARIANT$mp
24 libdispatch.dylib              0x183ce9d30 _dispatch_root_queue_drain
25 libdispatch.dylib              0x183ce9a80 _dispatch_worker_thread3
26 libsystem_pthread.dylib        0x18400ffac _pthread_wqthread + 1176
27 libsystem_pthread.dylib        0x18400fb08 start_wqthread + 4

#18. com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x183e4fe08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183e4fc80 mach_msg + 72
2  CoreFoundation                 0x184392e40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x184390908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x1842b0da8 CFRunLoopRunSpecific + 552
5  CoreFoundation                 0x184300b28 CFRunLoopRun + 116
6  CoreMotion                     0x1898919dc CLStartStopAdvertisingBeacon + 231572
7  libsystem_pthread.dylib        0x184011220 _pthread_body + 272
8  libsystem_pthread.dylib        0x184011110 _pthread_body + 290
9  libsystem_pthread.dylib        0x18400fb10 thread_start + 4
```

##Screen shots
screen shot 2018-05-24 at 11 32 39 am
screen shot 2018-05-24 at 11 36 48 am
screen shot 2018-05-24 at 11 37 24 am

## Steps to Reproduce
Realm data read or write producing this issue,  First my realm version was 3.0.2 at that time  **some users of app were facing this issue (not all users were facing this issue)**, Now i decided to upgrade library via cocoapod and mad 3.5.0 it is crashing on every build

## Code Sample

```
do {
try uiRealm.write {
uiRealm.add(response)
}
}
catch  {
print("could not write")
}
```

## Version of Realm and Tooling

Realm framework version: ? 3.5.0

Xcode version: Version 9.3 (9E145)

iOS/OSX version: 11.2.1 (iOS)

Dependency manager + version: CocoaPod 1.5.2

### PR DESCRIPTION
**Pull request by tgoyne**
#5713 made it so that optional Swift properties of a supported data type (i.e. `String?` and object links) which do not have ivars due to not being declared as `@objc dynamic` would crash rather than merely fail to actually read and update the managed value when the property is used.

The idea behavior here would be to throw an error on schema initialization as it's an invalid model declaration, but that's a breaking change (as such objects do work correctly when unmanaged), so for now this just restores the pre-3.5.0 behavior.

Fixes #5781.

### CODE REVIEW

File: Realm/RLMObjectStore.mm [hunk 1]
```diff
@@ -90,17 +90,24 @@ void RLMInitializeSwiftAccessorGenerics(__unsafe_unretained RLMObjectBase *const
     }
 
     for (RLMProperty *prop in object->_objectSchema.swiftGenericProperties) {
+        id ivar = object_getIvar(object, prop.swiftIvar);
+        if (!ivar) {
+            // FIXME: this should actually be an error as it's the result of an
```
Comment (cmelchior) [inline Realm/RLMObjectStore.mm]: Is there an issue tracking this, so we remember fixing it for the next major version?

File: Realm/RLMOptionalBase.mm [hunk 2]
```diff
@@ -123,6 +123,10 @@ - (void)doesNotRecognizeSelector:(SEL)aSelector {
 }
 
 id RLMGetOptional(__unsafe_unretained RLMOptionalBase *const self) {
+    if (!self) {
+        // FIXME: this should actually be an error
```
Comment (cmelchior) [inline Realm/RLMOptionalBase.mm]: Same as above. Link to issue.

File: Realm/RLMOptionalBase.mm [hunk 3]
```diff
@@ -132,6 +136,10 @@ id RLMGetOptional(__unsafe_unretained RLMOptionalBase *const self) {
 }
 
 void RLMSetOptional(__unsafe_unretained RLMOptionalBase *const self, __unsafe_unretained const id value) {
+    if (!self) {
+        // FIXME: this should actually be an error
```
Comment (cmelchior) [inline Realm/RLMOptionalBase.mm]: Same as above. Link to issue.
