### PR TITLE
Have +[RLMObjectSchema schemaForObjectClass:] throw an exception when…

### LINKED ISSUE #1844: Using duplicate property definitions in models should throw a more descriptive exception message
I can't instantiate Realm at all, I just get this assertion:

let r = Realm() // It fails already here!

Assertion failed: (props.count == [NSSet setWithArray:[props valueForKey:@"name"]].count), function +[RLMObjectSchema schemaForObjectClass:], file /Users/realmpro/workspace/Package iOS Swift/tightdb_objc/Realm/RLMObjectSchema.mm, line 102.

### PR DESCRIPTION
**Pull request by bdash**
… it sees the same property name multiple times for one class.

Fixes #1844.

/cc @segiddins @jpsim @tgoyne

### CODE REVIEW

**Comment by segiddins** [comment]
@bdash if you rebase atop master, you should now be able to test exception messages if you so wish.

File: Realm/RLMObjectSchema.mm [hunk 1]
```diff
@@ -99,7 +99,18 @@ + (instancetype)schemaForObjectClass:(Class)objectClass {
     schema.properties = props;
 
     // verify that we didn't add any properties twice due to inheritance
-    assert(props.count == [NSSet setWithArray:[props valueForKey:@"name"]].count);
+    if (props.count != [NSSet setWithArray:[props valueForKey:@"name"]].count) {
```
Comment (segiddins) [inline Realm/RLMObjectSchema.mm]: this could also be `[props valueForKeyPath:@"distinctUnionOfObjects.name"].count`, if you wanted to get cheeky

**Comment by segiddins** [comment]
:+1:

**Comment by bdash** [comment]
I'll take a look at testing exception messages more widely in a follow-up.
