### PR TITLE
Centralize exception creation

### LINKED ISSUE #1372: Using single code path for creating exceptions/Add library version to user info
Add the version text of the cocoa binding to all exceptions thrown from core. In RLMRealm:throw_objc_exception()
In likely doesn't make sense to include it in make_realm_error.

### LINKED ISSUE #1374: Centralize exception creation in a single function
Will make addressing https://github.com/realm/realm-cocoa/issues/1372 much easier.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #1374.
Closes #1372.

\c @alazier

### CODE REVIEW

File: Realm/RLMUtil.hpp [hunk 1]
```diff
@@ -27,6 +27,9 @@
 
 @class RLMProperty;
 
+NSException *RLMException(NSString *message, NSDictionary *userInfo = nil);
+NSException *RLMException(std::exception exception);
```
Comment (tgoyne) [inline Realm/RLMUtil.hpp]: `std::exception const& exception`

Passing polymorphic types by value doesn't work (you get a `std::exception` copy inside the function rather than a copy with the original type).

File: Realm/RLMUtil.mm [hunk 2]
```diff
@@ -238,3 +237,18 @@ id RLMValidatedObjectForProperty(id obj, RLMProperty *prop, RLMSchema *schema) {
     }
     return outArray;
 };
+
+NSException *RLMException(NSString *reason, NSDictionary *userInfo) {
+    NSMutableDictionary *info = [NSMutableDictionary dictionaryWithDictionary:userInfo];
```
Comment (tgoyne) [inline Realm/RLMUtil.mm]: Does this actually work when `userInfo` is `nil`? I would expect it to throw.

Comment (segiddins) [inline Realm/RLMUtil.mm]: That's what `dictionaryWithDictionary` is for, as opposed to `mutableCopy` -- it works when the parameter is `nil`.

File: Realm/RLMUtil.hpp (hunk 1 above)
Comment (segiddins) [inline Realm/RLMUtil.hpp]: done

File: Realm/RLMUtil.mm (hunk 2 above)
Comment (alazier) [inline Realm/RLMUtil.mm]: Can you add a test for this?

File: Realm/RLMRealm.mm [hunk 3]
```diff
@@ -71,8 +71,7 @@ - (void)notify;
 
 // create NSException from c++ exception
 static __attribute__((noreturn)) void throw_objc_exception(exception &ex) {
```
Comment (alazier) [inline Realm/RLMRealm.mm]: We should just remove this method and throw RLMException wherever this is called.

File: Realm/RLMRealm.mm [hunk 4]
```diff
@@ -71,8 +71,7 @@ - (void)notify;
...
-    NSString *errorMessage = [NSString stringWithUTF8String:ex.what()];
-    @throw [NSException exceptionWithName:@"RLMException" reason:errorMessage userInfo:nil];
+    @throw RLMException(ex);
 }
 
 // create NSError from c++ exception
```
Comment (alazier) [inline Realm/RLMRealm.mm]: Should convert make_realm_error to RLMError following the pattern used with RLMException.

File: Realm/RLMRealm.mm [hunk 5]
```diff
@@ -88,9 +87,7 @@ static void setOrThrowError(NSError *error, NSError **outError) {
         *outError = error;
```
Comment (alazier) [inline Realm/RLMRealm.mm]: Could make this method a utililty methods as well.

**Comment by alazier** [comment]
Overall looks good. Lets try to finish this up today to minimize conflicts.

File: Realm/RLMUtil.mm (hunk 2 above)
Comment (segiddins) [inline Realm/RLMUtil.mm]: There are currently no tests for the functionality in `RLMUtil`, should I add a new test file?

**Comment by segiddins** [comment]
@alazier added test coverage.

**Comment by alazier** [comment]
Couldn't we just make a function which returns bool and XCTAssertTrue? Would be a bit less confusing I think. Otherwise everything looks good to me.

**Comment by segiddins** [comment]
> Couldn't we just make a function which returns bool and XCTAssertTrue? Would be a bit less confusing I think.

Done.

**Comment by alazier** [comment]
:+1:
