### PR TITLE
Fix race conditions when an RLMRealm is deallocated from the wrong thread

### LINKED ISSUE #3013: Crash at advance_transact with version 0.97
backtrace is below:

``` backtrace
* thread #58: tid = 0x1b6d1a, 0x00000001047bc193 Realm`realm::Table::bump_version(bool) const + 131, queue = 'NSOperationQueue 0x7fb5cdea9460 :: NSOperation 0x7fb5cda57720 (QOS: UTILITY)', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00000001047bc193 Realm`realm::Table::bump_version(bool) const + 131
    frame #1: 0x00000001047bc199 Realm`realm::Table::bump_version(bool) const + 137
    frame #2: 0x00000001047bc199 Realm`realm::Table::bump_version(bool) const + 137
    frame #3: 0x00000001047bc199 Realm`realm::Table::bump_version(bool) const + 137
    frame #4: 0x00000001047dde62 Realm`realm::Group::advance_transact(unsigned long, unsigned long, realm::_impl::NoCopyInputStream&) + 610
  * frame #5: 0x00000001046e6e7d Realm`realm::_impl::GroupFriend::advance_transact(group=0x00007fb5cb9fbe00, new_top_ref=575872, new_file_size=589824, in=0x000000012028f1a8) + 45 at group.hpp:1186
    frame #6: 0x00000001046de59c Realm`void realm::SharedGroup::advance_read<(anonymous namespace)::TransactLogValidator>(this=0x00007fb5cb9fbe00, history=0x00007fb5cdb2b1f8, observer=0x000000012028f880, version=(version = 0, index = 0))::TransactLogValidator*, realm::SharedGroup::VersionID) + 1052 at group_shared.hpp:921
    frame #7: 0x00000001046de175 Realm`void realm::_impl::SharedGroupFriend::advance_read<(anonymous namespace)::TransactLogValidator>(sg=0x00007fb5cb9fbe00, hist=0x00007fb5cdb2b1f8, obs=0x000000012028f880, ver=(version = 0, index = 0))::TransactLogValidator*, realm::SharedGroup::VersionID) + 69 at group_shared.hpp:1081
    frame #8: 0x00000001046de125 Realm`void realm::LangBindHelper::advance_read<(anonymous namespace)::TransactLogValidator>(sg=0x00007fb5cb9fbe00, history=0x00007fb5cdb2b1f8, observer=0x000000012028f880, version=(version = 0, index = 0))::TransactLogValidator&&, realm::SharedGroup::VersionID) + 69 at lang_bind_helper.hpp:362
    frame #9: 0x00000001046de00a Realm`auto realm::_impl::transaction::advance(this=0x000000012028f870, args=0x000000012028f880)::$_0::operator()<(anonymous namespace)::TransactLogValidator&>((anonymous namespace)::TransactLogValidator&&&) const + 106 at transact_log_handler.cpp:437
    frame #10: 0x00000001046ddc0c Realm`(anonymous namespace)::TransactLogObserver::TransactLogObserver<realm::_impl::transaction::advance(this=0x000000012028f880, context=0x00007fb5cda85ff0, sg=0x00007fb5cb9fbe00, func=0x000000012028f870, validate_schema_changes=true)::$_0>(realm::BindingContext*, realm::SharedGroup&, realm::_impl::transaction::advance(realm::SharedGroup&, realm::ClientHistory&, realm::BindingContext*)::$_0&&, bool) + 1132 at transact_log_handler.cpp:221
    frame #11: 0x00000001046dd35e Realm`(anonymous namespace)::TransactLogObserver::TransactLogObserver<realm::_impl::transaction::advance(this=0x000000012028f880, context=0x00007fb5cda85ff0, sg=0x00007fb5cb9fbe00, func=0x000000012028f870, validate_schema_changes=true)::$_0>(realm::BindingContext*, realm::SharedGroup&, realm::_impl::transaction::advance(realm::SharedGroup&, realm::ClientHistory&, realm::BindingContext*)::$_0&&, bool) + 62 at transact_log_handler.cpp:203
    frame #12: 0x00000001046dd301 Realm`realm::_impl::transaction::advance(sg=0x00007fb5cb9fbe00, history=0x00007fb5cdb2b1b0, context=0x00007fb5cda85ff0) + 81 at transact_log_handler.cpp:436
    frame #13: 0x00000001046cd8d8 Realm`realm::Realm::notify(this=0x00007fb5cdbd4480) + 472 at shared_realm.cpp:368
    frame #14: 0x0000000104548a0c Realm`realm::_impl::ExternalCommitHelper::add_realm(this=0x00000001045489d0, info=0x00007fb5cdbd4480)::$_1::operator()(void*) const + 28 at external_commit_helper.cpp:256
    frame #15: 0x00000001045489e8 Realm`realm::_impl::ExternalCommitHelper::add_realm(info=0x00007fb5cdbd4480)::$_1::__invoke(void*) + 24 at external_commit_helper.cpp:255
    frame #16: 0x0000000105aa2011 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #17: 0x0000000105a97f3c CoreFoundation`__CFRunLoopDoSources0 + 556
    frame #18: 0x0000000105a973f3 CoreFoundation`__CFRunLoopRun + 867
    frame #19: 0x0000000105a96e08 CoreFoundation`CFRunLoopRunSpecific + 488
    frame #20: 0x0000000105b49ff1 CoreFoundation`CFRunLoopRun + 97
    frame #21: 0x0000000104b7a73c SDWebImage`-[SDWebImageDownloaderOperation start](self=0x00007fb5cda57720, _cmd="start") + 1868 at SDWebImageDownloaderOperation.m:117
    frame #22: 0x0000000104e7ac47 Foundation`__NSOQSchedule_f + 194
    frame #23: 0x000000010886849b libdispatch.dylib`_dispatch_client_callout + 8
    frame #24: 0x000000010884e8ec libdispatch.dylib`_dispatch_queue_drain + 2215
    frame #25: 0x000000010884de0d libdispatch.dylib`_dispatch_queue_invoke + 601
    frame #26: 0x0000000108850a56 libdispatch.dylib`_dispatch_root_queue_drain + 1420
    frame #27: 0x00000001088504c5 libdispatch.dylib`_dispatch_worker_thread3 + 111
    frame #28: 0x0000000108bb0a9d libsystem_pthread.dylib`_pthread_wqthread + 729
    frame #29: 0x0000000108bae3dd libsystem_pthread.dylib`start_wqthread + 13

```

### PR DESCRIPTION
**Pull request by tgoyne**
The runloop notification source needs to hold a strong reference while the block is running and a zeroing weak reference the rest of the time to handle `CFRunLoopSourceInvalidate()` being called from a different thread.

Similarly, RLMNotificationHelper needs a zeroing weak reference to the RLMRealm because the SharedRealm can outlive the RLMRealm and then crash when it tries to deliver a notification to the RLMRealm. The reads of the weak pointer are in autoreleasepools because ARC autoreleases pointers when acquiring a strong reference to a weak pointer.

Fixes #3013.

### CODE REVIEW

**Comment by bdash** [comment]
Any chance of a test case that reproduces #1424, or does hitting the issue involve too much luck with timing?

**Comment by tgoyne** [comment]
I don't have any idea how to meaningfully test it deterministically, and the time to hit a crash the brute-force way varied from a few seconds to a few minutes.

File: Realm/ObjectStore/impl/apple/external_commit_helper.cpp [hunk 1]
```diff
@@ -249,11 +249,28 @@ void ExternalCommitHelper::add_realm(realm::Realm* realm)
...
+            realm->notify();
+        }
+    };
+    ctx.retain = [](const void* info) {
+        static_cast<RefCountedWeakPointer*>(const_cast<void*>(info))->ref_count.fetch_add(1, std::memory_order_relaxed);
+        return info;
+    };
+    ctx.release = [](const void* info) {
+        auto ptr = static_cast<RefCountedWeakPointer*>(const_cast<void*>(info));
+        if (ptr->ref_count.fetch_add(-1, std::memory_order_relaxed) == 1) {
```
Comment (bdash) [inline Realm/ObjectStore/impl/apple/external_commit_helper.cpp]: The use of `memory_order_relaxed` in the release operation is a little non-obvious. I'm used to seeing relaxed used in retain and release / acquire in release. Can you explain why relaxed is sufficient here?

Comment (tgoyne) [inline Realm/ObjectStore/impl/apple/external_commit_helper.cpp]: Nothing that's being used in this function or the destructor is dependent on synchronization from the ref count so it's fine for the loads to be reordered, but there's really no reason to be clever here, so I'll switch it to acq_rel.

**Comment by bdash** [comment]
:+1:
