### PR TITLE
Fix use of nested subqueries

### LINKED ISSUE #4469: NSPredicate nested subqueries crash
## Goals

I'm trying to achieve filtering using a predicate which contains nested subqueries. Here is the predicate which I'm working with:

```
SUBQUERY(projects, $p, $p.typeGroup.id == 75 AND SUBQUERY($p.subProjects, $sp, ANY $sp.teamMembers.initials == \"SUP\" AND $sp.statusString == \"ACTIVE\").@count > 0).@count > 0
```

## Expected Results

I expected it to return the same result as the predicate returns when run with NSPredicate.

## Actual Results

It crashed:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -operand only defined for abstract class.  Define -[NSSubqueryExpression operand]!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001024aed4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000101f1021e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001025182b5 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000101b0dd56 NSRequestConcreteImplementation + 229
	4   Foundation                          0x0000000101b6f22b -[NSExpression operand] + 39
	5   Realm                               0x00000001012db2e4 _ZNK12_GLOBAL__N_130PredicateExpressionTransformer5visitEP12NSExpression + 1256
	6   Realm                               0x00000001012db03e _ZNK12_GLOBAL__N_130PredicateExpressionTransformer5visitEP12NSExpression + 578
	7   Realm                               0x00000001012dac13 _ZNK12_GLOBAL__N_130PredicateExpressionTransformer5visitEP11NSPredicate + 691
	8   Realm                               0x00000001012daac6 _ZNK12_GLOBAL__N_130PredicateExpressionTransformer5visitEP11NSPredicate + 358
	9   Realm                               0x00000001012da943 _Z18transformPredicateP11NSPredicatePFP12NSExpressionS2_E + 27
	10  Realm                               0x000000010133d411 _ZN12_GLOBAL__N_112QueryBuilder34apply_function_subquery_expressionEP15RLMObjectSchemaP12NSExpression23NSPredicateOperatorTypeS4_ + 1091
	11  Realm                               0x00000001012df101 _ZN12_GLOBAL__N_112QueryBuilder15apply_predicateEP11NSPredicateP15RLMObjectSchema + 3247
	12  Realm                               0x00000001012de2c2 _Z19RLMPredicateToQueryP11NSPredicateP15RLMObjectSchemaP9RLMSchemaRN5realm5GroupE + 154
	13  Realm                               0x0000000101345b40 -[RLMResults objectsWithPredicate:] + 162
	14  RealmSwift                          0x00000001018a0cac _TFC10RealmSwift7Results6filterfCSo11NSPredicateGS0_x_ + 92
	15  MyApp                              0x0000000100b1ef26 _TFFC6MyApp18DashboardViewModelcFT_S0_U4_FTGSqSS_SSGSqOS_17ApplicationFilter__GVS_31AnyReactiveCollectionDataSourceSSVS_15ProjectCellInfo_ + 3718
```

## Steps to Reproduce

I don't currently have the time to setup a test project. But if you can't reproduce it, I'll try to find some time next week.

## Code Sample

Nothing for now.

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D12b

/Applications/Xcode.app/Contents/Developer
Xcode 8.2
Build version 8C38

/Users/david/.rbenv/shims/pod
1.1.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18.1
github "realm/realm-cocoa" "v2.1.1"

/usr/bin/git
git version 2.10.1 (Apple Git-78)
```

### PR DESCRIPTION
**Pull request by bdash**
The code to visit the expressions within a subquery expression was incorrectly accessing the `operand` property instead of the `collection` property, resulting in an exception being thrown.

Fixes #4469 and #3675.

### CODE REVIEW

File: Realm/Tests/PredicateUtilTests.mm [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+#import "RLMPredicateUtil.hpp"
+
+@interface PredicateUtilTests : RLMTestCase
+
+@end
+
+@implementation PredicateUtilTests
+
+- (void)testVisitingAllExpresssionTypes {
```
Comment (jpsim) [inline Realm/Tests/PredicateUtilTests.mm]: "Expresssion" -> "Expression"

File: Realm/Tests/PredicateUtilTests.mm [hunk 2]
```diff
@@ -0,0 +1,59 @@
+//
```
Comment (jpsim) [inline Realm/Tests/PredicateUtilTests.mm]: Wrong comment header

File: Realm/RLMPredicateUtil.mm [hunk 3]
```diff
@@ -72,8 +74,12 @@ - (NSExpression *)falseExpression;
         case NSMinusSetExpressionType:
             return [NSExpression expressionForMinusSet:visit(expression.leftExpression) with:visit(expression.rightExpression)];
 
-        case NSSubqueryExpressionType:
-            return [NSExpression expressionForSubquery:visit(expression.operand) usingIteratorVariable:expression.variable predicate:visit(expression.predicate)];
+        case NSSubqueryExpressionType: {
+            NSExpression *collection = expression.collection;
+            // NSExpression.collection is declared as id, but appears to always hold an NSExpression for subqueries.
+            REALM_ASSERT([collection isKindOfClass:[NSExpression class]]);
```
Comment (jpsim) [inline Realm/RLMPredicateUtil.mm]: `REALM_ASSERT_DEBUG`?

Comment (bdash) [inline Realm/RLMPredicateUtil.mm]: I went with `REALM_ASSERT` here because we're only likely to discover this assumption is wrong when a user runs into this, and users don't often use debug versions of the Realm framework.

Comment (tgoyne) [inline Realm/RLMPredicateUtil.mm]: `REALM_ASSERT_DEBUG()` should only be used if the check is too expensive to include in release builds.

**Comment by bdash** [comment]
The CI failures all appear to be issues with CI.
