### PR TITLE
[Results] `Results` now conforms to `CVarArgType`.

### LINKED ISSUE #1995: Make Results and List conform to CVarArgType
Currently, the following code fails to compile:

```swift
Realm().objects(Company).filter("ANY employees IN %@", realm.objects(Employee))
```

Because `Results` doesn't conform to `CVarArgType`. The simplest workaround for now is to convert the `Results` into an `Array` like so:

```swift
Realm().objects(Company).filter("ANY employees IN %@", map(realm.objects(Employee), { $0 }))
```

But the proper solution would be to make `Results` and `List` conform to `CVarArgType`.

### PR DESCRIPTION
**Pull request by jpsim**
Fixes #1995. `List` already conforms to `CVarArgType` because it inherits from `NSObject`. /cc @tgoyne @bdash @segiddins

### CODE REVIEW

File: RealmSwift/Results.swift [hunk 1]
```diff
@@ -284,3 +284,13 @@ extension Results: CollectionType {
...
     public var endIndex: Int { return count }
 }
+
+// MARK: Variadic Arguments Support
+
+extension Results: CVarArgType {
+    /// Transform `self` into a series of machine words that can be
+    /// appropriately interpreted by C varargs
+    public func encode() -> [Word] {
+        return (map(self, { $0 }) as NSArray).encode()
```
Comment (segiddins) [inline RealmSwift/Results.swift]: Why not return `rlmResults.encode()`

Comment (jpsim) [inline RealmSwift/Results.swift]: Because that would just be way too simple! /jk, will do. it hadn't occurred to me.

**Comment by tgoyne** [comment]
:+1:
